version: "3.8"

# Simplified compose file for Dokploy - uses Dokploy's managed databases
# This file ONLY includes app services (ehr-api, ehr-web, keycloak)
# Database, Redis are managed separately in Dokploy

services:
  redis:
    image: redis:7-alpine
    container_name: ehr-redis-dev
    networks:
      - ehr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: ehr-keycloak-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    networks:
      - ehr-network
    command:
      - start
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/themes:/opt/keycloak/providers/
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  ehr-api:
    image: ${DOCKERHUB_USERNAME:-jitendratech}/ehr-api:${API_IMAGE_TAG:-dev}
    container_name: ehr-api-dev
    environment:
      NODE_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-ehr-realm}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_CLIENT_ID: admin-cli
      PORT: 8000
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      SOCKET_IO_ENABLED: "true"
      SOCKET_PORT: 8001
      SOCKET_CORS_ORIGIN: ${ALLOWED_ORIGINS}
      CLAIMMD_API_URL: ${CLAIMMD_API_URL:-https://api.claim.md/v1}
    depends_on:
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - ehr-network
    restart: unless-stopped

  ehr-web:
    image: ${DOCKERHUB_USERNAME:-jitendratech}/ehr-web:${WEB_IMAGE_TAG:-dev}
    container_name: ehr-web-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}
      DIRECT_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}
      REDIS_URL: redis://redis:6379
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_KEYCLOAK_URL: ${NEXT_PUBLIC_KEYCLOAK_URL}
      NEXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM:-ehr-realm}
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${NEXT_PUBLIC_KEYCLOAK_CLIENT_ID}
    depends_on:
      - ehr-api
      - redis
    networks:
      - ehr-network
    restart: unless-stopped

networks:
  ehr-network:
    driver: bridge
