import { ThemeSettings } from '@/contexts/theme-context';

export interface PresetTheme extends ThemeSettings {
    id: string;
    name: string;
    category: 'Modern' | 'Classic' | 'Special' | 'Dark';
}

export const PRESET_THEMES: PresetTheme[] = [
    {
        id: 'default-blue',
        name: 'Default Blue',
        category: 'Modern',
        primaryColor: '#4A90E2',
        secondaryColor: '#9B59B6',
        sidebarBackgroundColor: '#0F1E56',
        sidebarTextColor: '#B0B7D0',
        sidebarActiveColor: '#3342A5',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'medical-teal',
        name: 'Medical Teal',
        category: 'Special',
        primaryColor: '#0D9488',
        secondaryColor: '#0F766E',
        sidebarBackgroundColor: '#115E59',
        sidebarTextColor: '#CCFBF1',
        sidebarActiveColor: '#14B8A6',
        accentColor: '#F59E0B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-ocean',
        name: 'Deep Ocean',
        category: 'Dark',
        primaryColor: '#3B82F6',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#111827',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#1F2937',
        accentColor: '#60A5FA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'magenta-pulse',
        name: 'Magenta Pulse',
        category: 'Special',
        primaryColor: '#D946EF',
        secondaryColor: '#A21CAF',
        sidebarBackgroundColor: '#4A044E',
        sidebarTextColor: '#FAE8FF',
        sidebarActiveColor: '#701A75',
        accentColor: '#F472B6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'forest-green',
        name: 'Evergreen forest',
        category: 'Modern',
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#34D399',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sunset-blaze',
        name: 'Sunset Blaze',
        category: 'Special',
        primaryColor: '#F97316',
        secondaryColor: '#EA580C',
        sidebarBackgroundColor: '#7C2D12',
        sidebarTextColor: '#FFEDD5',
        sidebarActiveColor: '#9A3412',
        accentColor: '#FB923C',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-business',
        name: 'Professional Slate',
        category: 'Classic',
        primaryColor: '#475569',
        secondaryColor: '#334155',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1E293B',
        accentColor: '#64748B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'royal-velvet',
        name: 'Royal Velvet',
        category: 'Classic',
        primaryColor: '#7C3AED',
        secondaryColor: '#6D28D9',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#A78BFA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'nordic-ice',
        name: 'Nordic Ice',
        category: 'Modern',
        primaryColor: '#0EA5E9',
        secondaryColor: '#0284C7',
        sidebarBackgroundColor: '#F8FAFC',
        sidebarTextColor: '#475569',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'cyberpunk-neon',
        name: 'Cyber Neon',
        category: 'Dark',
        primaryColor: '#FF00FF',
        secondaryColor: '#00FFFF',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FF00FF',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#00FF00',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'midnight-minimal',
        name: 'Midnight',
        category: 'Dark',
        primaryColor: '#FFFFFF',
        secondaryColor: '#E5E7EB',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#111111',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'earth-warmth',
        name: 'Earth Warmth',
        category: 'Modern',
        primaryColor: '#B45309',
        secondaryColor: '#92400E',
        sidebarBackgroundColor: '#451A03',
        sidebarTextColor: '#FEF3C7',
        sidebarActiveColor: '#78350F',
        accentColor: '#F59E0B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'obsidian-gold',
        name: 'Obsidian Gold',
        category: 'Classic',
        primaryColor: '#FBBF24',
        secondaryColor: '#D97706',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FDE68A',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#B45309',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'clean-hospital',
        name: 'Sterile Clean',
        category: 'Classic',
        primaryColor: '#2563EB',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#1E293B',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'amethyst-dream',
        name: 'Amethyst',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#7C3AED',
        sidebarBackgroundColor: '#1E1B4B',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#312E81',
        accentColor: '#C084FC',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'ruby-rose',
        name: 'Ruby Rose',
        category: 'Special',
        primaryColor: '#E11D48',
        secondaryColor: '#BE123C',
        sidebarBackgroundColor: '#4C0519',
        sidebarTextColor: '#FFE4E6',
        sidebarActiveColor: '#881337',
        accentColor: '#FB7185',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emerald-city',
        name: 'Emerald City',
        category: 'Modern',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'monochrome-professional',
        name: 'High Contrast',
        category: 'Special',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#000000',
        sidebarActiveColor: '#EEEEEE',
        accentColor: '#666666',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    }
];
