import { ThemeSettings } from '@/contexts/theme-context';

export interface PresetTheme extends ThemeSettings {
    id: string;
    name: string;
    category: 'Modern' | 'Classic' | 'Special' | 'Dark';
}

export const PRESET_THEMES: PresetTheme[] = [
    {
        id: 'default-blue',
        name: 'Default Blue',
        category: 'Modern',
        primaryColor: '#4A90E2',
        secondaryColor: '#9B59B6',
        sidebarBackgroundColor: '#0F1E56',
        sidebarTextColor: '#B0B7D0',
        sidebarActiveColor: '#3342A5',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'medical-teal',
        name: 'Medical Teal',
        category: 'Special',
        primaryColor: '#0D9488',
        secondaryColor: '#0F766E',
        sidebarBackgroundColor: '#115E59',
        sidebarTextColor: '#CCFBF1',
        sidebarActiveColor: '#14B8A6',
        accentColor: '#F59E0B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-ocean',
        name: 'Deep Ocean',
        category: 'Dark',
        primaryColor: '#3B82F6',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#111827',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#1F2937',
        accentColor: '#60A5FA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'magenta-pulse',
        name: 'Magenta Pulse',
        category: 'Special',
        primaryColor: '#D946EF',
        secondaryColor: '#A21CAF',
        sidebarBackgroundColor: '#4A044E',
        sidebarTextColor: '#FAE8FF',
        sidebarActiveColor: '#701A75',
        accentColor: '#F472B6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'forest-green',
        name: 'Evergreen forest',
        category: 'Modern',
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#34D399',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sunset-blaze',
        name: 'Sunset Blaze',
        category: 'Special',
        primaryColor: '#F97316',
        secondaryColor: '#EA580C',
        sidebarBackgroundColor: '#7C2D12',
        sidebarTextColor: '#FFEDD5',
        sidebarActiveColor: '#9A3412',
        accentColor: '#FB923C',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-business',
        name: 'Professional Slate',
        category: 'Classic',
        primaryColor: '#475569',
        secondaryColor: '#334155',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1E293B',
        accentColor: '#64748B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'royal-velvet',
        name: 'Royal Velvet',
        category: 'Classic',
        primaryColor: '#7C3AED',
        secondaryColor: '#6D28D9',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#A78BFA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'nordic-ice',
        name: 'Nordic Ice',
        category: 'Modern',
        primaryColor: '#0EA5E9',
        secondaryColor: '#0284C7',
        sidebarBackgroundColor: '#F8FAFC',
        sidebarTextColor: '#475569',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'cyberpunk-neon',
        name: 'Cyber Neon',
        category: 'Dark',
        primaryColor: '#FF00FF',
        secondaryColor: '#00FFFF',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FF00FF',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#00FF00',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'midnight-minimal',
        name: 'Midnight',
        category: 'Dark',
        primaryColor: '#FFFFFF',
        secondaryColor: '#E5E7EB',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#111111',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'earth-warmth',
        name: 'Earth Warmth',
        category: 'Modern',
        primaryColor: '#B45309',
        secondaryColor: '#92400E',
        sidebarBackgroundColor: '#451A03',
        sidebarTextColor: '#FEF3C7',
        sidebarActiveColor: '#78350F',
        accentColor: '#F59E0B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'obsidian-gold',
        name: 'Obsidian Gold',
        category: 'Classic',
        primaryColor: '#FBBF24',
        secondaryColor: '#D97706',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FDE68A',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#B45309',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'clean-hospital',
        name: 'Sterile Clean',
        category: 'Classic',
        primaryColor: '#2563EB',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#1E293B',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'amethyst-dream',
        name: 'Amethyst',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#7C3AED',
        sidebarBackgroundColor: '#1E1B4B',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#312E81',
        accentColor: '#C084FC',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'ruby-rose',
        name: 'Ruby Rose',
        category: 'Special',
        primaryColor: '#E11D48',
        secondaryColor: '#BE123C',
        sidebarBackgroundColor: '#4C0519',
        sidebarTextColor: '#FFE4E6',
        sidebarActiveColor: '#881337',
        accentColor: '#FB7185',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emerald-city',
        name: 'Emerald City',
        category: 'Modern',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'monochrome-professional',
        name: 'High Contrast',
        category: 'Special',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#000000',
        sidebarActiveColor: '#EEEEEE',
        accentColor: '#666666',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- BLUE SERIES (EXECUTIVE & MODERN) ---
    {
        id: 'executive-navy',
        name: 'Executive Navy',
        category: 'Classic',
        primaryColor: '#1E293B',
        secondaryColor: '#334155',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1E293B',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'royal-azure',
        name: 'Royal Azure',
        category: 'Modern',
        primaryColor: '#2563EB',
        secondaryColor: '#1D4ED8',
        sidebarBackgroundColor: '#1E3A8A',
        sidebarTextColor: '#BFDBFE',
        sidebarActiveColor: '#2563EB',
        accentColor: '#60A5FA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-corporate',
        name: 'Slate Corporate',
        category: 'Classic',
        primaryColor: '#475569',
        secondaryColor: '#64748B',
        sidebarBackgroundColor: '#1E293B',
        sidebarTextColor: '#CBD5E1',
        sidebarActiveColor: '#334155',
        accentColor: '#94A3B8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'indigo-trust',
        name: 'Indigo Trust',
        category: 'Modern',
        primaryColor: '#4F46E5',
        secondaryColor: '#4338CA',
        sidebarBackgroundColor: '#312E81',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#4F46E5',
        accentColor: '#818CF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sky-clinical',
        name: 'Sky Clinical',
        category: 'Modern',
        primaryColor: '#0EA5E9',
        secondaryColor: '#0284C7',
        sidebarBackgroundColor: '#F0F9FF',
        sidebarTextColor: '#0369A1',
        sidebarActiveColor: '#E0F2FE',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- DARK MODE SERIES (PREMIUM & DEEP) ---
    {
        id: 'obsidian-night',
        name: 'True Obsidian',
        category: 'Dark',
        primaryColor: '#FFFFFF',
        secondaryColor: '#E2E8F0',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#111111',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'charcoal-pro',
        name: 'Charcoal Pro',
        category: 'Dark',
        primaryColor: '#F8FAFC',
        secondaryColor: '#CBD5E1',
        sidebarBackgroundColor: '#121212',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1F1F1F',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'midnight-neon',
        name: 'Midnight Neon',
        category: 'Dark',
        primaryColor: '#A855F7',
        secondaryColor: '#D946EF',
        sidebarBackgroundColor: '#09090B',
        sidebarTextColor: '#A1A1AA',
        sidebarActiveColor: '#18181B',
        accentColor: '#FF00FF',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'outer-space',
        name: 'Outer Space',
        category: 'Dark',
        primaryColor: '#60A5FA',
        secondaryColor: '#3B82F6',
        sidebarBackgroundColor: '#020617',
        sidebarTextColor: '#64748B',
        sidebarActiveColor: '#0F172A',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dracula-clinical',
        name: 'Dracula Clinical',
        category: 'Dark',
        primaryColor: '#BD93F9',
        secondaryColor: '#FF79C6',
        sidebarBackgroundColor: '#282A36',
        sidebarTextColor: '#F8F8F2',
        sidebarActiveColor: '#44475A',
        accentColor: '#50FA7B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- MEDICAL & CLINICAL ---
    {
        id: 'sterile-white',
        name: 'Sterile White',
        category: 'Classic',
        primaryColor: '#2563EB',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#334155',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'health-green',
        name: 'Health Green',
        category: 'Modern',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        sidebarBackgroundColor: '#ECFDF5',
        sidebarTextColor: '#065F46',
        sidebarActiveColor: '#D1FAE5',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emergency-red',
        name: 'Care Red',
        category: 'Special',
        primaryColor: '#DC2626',
        secondaryColor: '#B91C1C',
        sidebarBackgroundColor: '#FEF2F2',
        sidebarTextColor: '#991B1B',
        sidebarActiveColor: '#FEE2E2',
        accentColor: '#EF4444',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'teal-wellness',
        name: 'Teal Wellness',
        category: 'Modern',
        primaryColor: '#0D9488',
        secondaryColor: '#0F766E',
        sidebarBackgroundColor: '#115E59',
        sidebarTextColor: '#CCFBF1',
        sidebarActiveColor: '#14B8A6',
        accentColor: '#F59E0B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- VIBRANT & UNIQUE ---
    {
        id: 'magenta-premium',
        name: 'Magenta Premium',
        category: 'Special',
        primaryColor: '#D946EF',
        secondaryColor: '#C026D3',
        sidebarBackgroundColor: '#4A044E',
        sidebarTextColor: '#FAE8FF',
        sidebarActiveColor: '#701A75',
        accentColor: '#F472B6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'violet-velvet',
        name: 'Violet Velvet',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#7C3AED',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#A78BFA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sunset-care',
        name: 'Sunset Care',
        category: 'Special',
        primaryColor: '#F97316',
        secondaryColor: '#EA580C',
        sidebarBackgroundColor: '#FFF7ED',
        sidebarTextColor: '#9A3412',
        sidebarActiveColor: '#FFEDD5',
        accentColor: '#FB923C',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'earth-organic',
        name: 'Earth Organic',
        category: 'Classic',
        primaryColor: '#78350F',
        secondaryColor: '#92400E',
        sidebarBackgroundColor: '#FEF3C7',
        sidebarTextColor: '#451A03',
        sidebarActiveColor: '#FDE68A',
        accentColor: '#B45309',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'nordic-minimal',
        name: 'Nordic Minimal',
        category: 'Modern',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#F8FAFC',
        sidebarTextColor: '#475569',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#64748B',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'rose-gold-premium',
        name: 'Rose Gold',
        category: 'Special',
        primaryColor: '#BE123C',
        secondaryColor: '#E11D48',
        sidebarBackgroundColor: '#FFF1F2',
        sidebarTextColor: '#9F1239',
        sidebarActiveColor: '#FFE4E6',
        accentColor: '#FB7185',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emerald-luxury',
        name: 'Emerald Luxury',
        category: 'Classic',
        primaryColor: '#064E3B',
        secondaryColor: '#065F46',
        sidebarBackgroundColor: '#022C22',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#064E3B',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'gold-obsidian',
        name: 'Gold Obsidian',
        category: 'Dark',
        primaryColor: '#EAB308',
        secondaryColor: '#CA8A04',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FEF9C3',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#FACC15',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'oceanic-breeze',
        name: 'Oceanic Breeze',
        category: 'Modern',
        primaryColor: '#0891B2',
        secondaryColor: '#0E7490',
        sidebarBackgroundColor: '#ECFEFF',
        sidebarTextColor: '#164E63',
        sidebarActiveColor: '#CFFAFE',
        accentColor: '#22D3EE',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'lavender-mist',
        name: 'Lavender Mist',
        category: 'Modern',
        primaryColor: '#7C3AED',
        secondaryColor: '#8B5CF6',
        sidebarBackgroundColor: '#F5F3FF',
        sidebarTextColor: '#5B21B6',
        sidebarActiveColor: '#EDE9FE',
        accentColor: '#A78BFA',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'carbon-fiber',
        name: 'Carbon Fiber',
        category: 'Dark',
        primaryColor: '#3F3F46',
        secondaryColor: '#27272A',
        sidebarBackgroundColor: '#18181B',
        sidebarTextColor: '#D4D4D8',
        sidebarActiveColor: '#27272A',
        accentColor: '#71717A',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'candy-clinical',
        name: 'Candy Clinical',
        category: 'Special',
        primaryColor: '#F43F5E',
        secondaryColor: '#E11D48',
        sidebarBackgroundColor: '#FFF1F2',
        sidebarTextColor: '#BE123C',
        sidebarActiveColor: '#FFE4E6',
        accentColor: '#FB7185',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'arctic-night',
        name: 'Arctic Night',
        category: 'Dark',
        primaryColor: '#BAE6FD',
        secondaryColor: '#7DD3FC',
        sidebarBackgroundColor: '#0C4A6E',
        sidebarTextColor: '#F0F9FF',
        sidebarActiveColor: '#075985',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'deep-purple-premium',
        name: 'Deep Purple',
        category: 'Classic',
        primaryColor: '#4C1D95',
        secondaryColor: '#5B21B6',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'forest-premium',
        name: 'Royal Forest',
        category: 'Classic',
        primaryColor: '#065F46',
        secondaryColor: '#064E3B',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-pro-dark',
        name: 'Slate Pro Dark',
        category: 'Dark',
        primaryColor: '#94A3B8',
        secondaryColor: '#64748B',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#F8FAFC',
        sidebarActiveColor: '#1E293B',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'executive-classic-blue',
        name: 'Executive Classic',
        category: 'Classic',
        primaryColor: '#1D4ED8',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#1E3A8A',
        sidebarTextColor: '#DBEAFE',
        sidebarActiveColor: '#2563EB',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'luxury-gold',
        name: 'Pure Gold',
        category: 'Special',
        primaryColor: '#D4AF37',
        secondaryColor: '#B8860B',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FFD700',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#FFD700',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'mint-clinical',
        name: 'Mint Clinical',
        category: 'Modern',
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        sidebarBackgroundColor: '#F0FDF4',
        sidebarTextColor: '#166534',
        sidebarActiveColor: '#DCFCE7',
        accentColor: '#34D399',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'deep-charcoal',
        name: 'Deep Charcoal',
        category: 'Dark',
        primaryColor: '#F9FAFB',
        secondaryColor: '#F3F4F6',
        sidebarBackgroundColor: '#111827',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#1F2937',
        accentColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-glass',
        name: 'Glass Modern',
        category: 'Modern',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#000000',
        sidebarActiveColor: '#F3F4F6',
        accentColor: '#000000',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'pacific-blue',
        name: 'Pacific Blue',
        category: 'Classic',
        primaryColor: '#0284C7',
        secondaryColor: '#0369A1',
        sidebarBackgroundColor: '#0C4A6E',
        sidebarTextColor: '#E0F2FE',
        sidebarActiveColor: '#075985',
        accentColor: '#38BDF8',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    }
];
