import { ThemeSettings } from '@/contexts/theme-context';

export interface PresetTheme extends ThemeSettings {
    id: string;
    name: string;
    category: 'Modern' | 'Classic' | 'Special' | 'Dark' | 'EMR';
}

export const PRESET_THEMES: PresetTheme[] = [
    {
        id: 'default-blue',
        name: 'Default Blue',
        category: 'Modern',
        primaryColor: '#4A90E2',
        secondaryColor: '#9B59B6',
        sidebarBackgroundColor: '#0F1E56',
        sidebarTextColor: '#B0B7D0',
        sidebarActiveColor: '#3342A5',
        accentColor: '#10B981',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#A855F7',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'medical-teal',
        name: 'Medical Teal',
        category: 'Special',
        primaryColor: '#0D9488',
        secondaryColor: '#0F766E',
        sidebarBackgroundColor: '#115E59',
        sidebarTextColor: '#CCFBF1',
        sidebarActiveColor: '#14B8A6',
        accentColor: '#F59E0B',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#06B6D4',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-ocean',
        name: 'Deep Ocean',
        category: 'Dark',
        primaryColor: '#3B82F6',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#111827',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#1F2937',
        accentColor: '#60A5FA',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'magenta-pulse',
        name: 'Magenta Pulse',
        category: 'Special',
        primaryColor: '#D946EF',
        secondaryColor: '#A21CAF',
        sidebarBackgroundColor: '#4A044E',
        sidebarTextColor: '#FAE8FF',
        sidebarActiveColor: '#701A75',
        accentColor: '#F472B6',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'forest-green',
        name: 'Evergreen forest',
        category: 'Modern',
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#34D399',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sunset-blaze',
        name: 'Sunset Blaze',
        category: 'Special',
        primaryColor: '#F97316',
        secondaryColor: '#EA580C',
        sidebarBackgroundColor: '#7C2D12',
        sidebarTextColor: '#FFEDD5',
        sidebarActiveColor: '#9A3412',
        accentColor: '#FB923C',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#D946EF',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-business',
        name: 'Professional Slate',
        category: 'Classic',
        primaryColor: '#475569',
        secondaryColor: '#334155',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1E293B',
        accentColor: '#64748B',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'royal-velvet',
        name: 'Royal Velvet',
        category: 'Classic',
        primaryColor: '#7C3AED',
        secondaryColor: '#6D28D9',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#A78BFA',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'nordic-ice',
        name: 'Nordic Ice',
        category: 'Modern',
        primaryColor: '#0EA5E9',
        secondaryColor: '#0284C7',
        sidebarBackgroundColor: '#F8FAFC',
        sidebarTextColor: '#475569',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#38BDF8',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'cyberpunk-neon',
        name: 'Cyber Neon',
        category: 'Dark',
        primaryColor: '#FF00FF',
        secondaryColor: '#00FFFF',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FF00FF',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#00FF00',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'midnight-minimal',
        name: 'Midnight',
        category: 'Dark',
        primaryColor: '#FFFFFF',
        secondaryColor: '#E5E7EB',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#111111',
        accentColor: '#3B82F6',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#A855F7',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'earth-warmth',
        name: 'Earth Warmth',
        category: 'Modern',
        primaryColor: '#B45309',
        secondaryColor: '#92400E',
        sidebarBackgroundColor: '#451A03',
        sidebarTextColor: '#FEF3C7',
        sidebarActiveColor: '#78350F',
        accentColor: '#F59E0B',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'obsidian-gold',
        name: 'Obsidian Gold',
        category: 'Classic',
        primaryColor: '#FBBF24',
        secondaryColor: '#D97706',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FDE68A',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#B45309',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#F43F5E',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'clean-hospital',
        name: 'Sterile Clean',
        category: 'Classic',
        primaryColor: '#2563EB',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#1E293B',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#3B82F6',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'amethyst-dream',
        name: 'Amethyst',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#7C3AED',
        sidebarBackgroundColor: '#1E1B4B',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#312E81',
        accentColor: '#C084FC',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'ruby-rose',
        name: 'Ruby Rose',
        category: 'Special',
        primaryColor: '#E11D48',
        secondaryColor: '#BE123C',
        sidebarBackgroundColor: '#4C0519',
        sidebarTextColor: '#FFE4E6',
        sidebarActiveColor: '#881337',
        accentColor: '#FB7185',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emerald-city',
        name: 'Emerald City',
        category: 'Modern',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#10B981',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#7C3AED',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'monochrome-professional',
        name: 'High Contrast',
        category: 'Special',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#000000',
        sidebarActiveColor: '#EEEEEE',
        accentColor: '#666666',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- BLUE SERIES (EXECUTIVE & MODERN) ---
    {
        id: 'executive-navy',
        name: 'Executive Navy',
        category: 'Classic',
        primaryColor: '#1E293B',
        secondaryColor: '#334155',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1E293B',
        accentColor: '#38BDF8',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'royal-azure',
        name: 'Royal Azure',
        category: 'Modern',
        primaryColor: '#2563EB',
        secondaryColor: '#1D4ED8',
        sidebarBackgroundColor: '#1E3A8A',
        sidebarTextColor: '#BFDBFE',
        sidebarActiveColor: '#2563EB',
        accentColor: '#60A5FA',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-corporate',
        name: 'Slate Corporate',
        category: 'Classic',
        primaryColor: '#475569',
        secondaryColor: '#64748B',
        sidebarBackgroundColor: '#1E293B',
        sidebarTextColor: '#CBD5E1',
        sidebarActiveColor: '#334155',
        accentColor: '#94A3B8',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'indigo-trust',
        name: 'Indigo Trust',
        category: 'Modern',
        primaryColor: '#4F46E5',
        secondaryColor: '#4338CA',
        sidebarBackgroundColor: '#312E81',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#4F46E5',
        accentColor: '#818CF8',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sky-clinical',
        name: 'Sky Clinical',
        category: 'Modern',
        primaryColor: '#0EA5E9',
        secondaryColor: '#0284C7',
        sidebarBackgroundColor: '#F0F9FF',
        sidebarTextColor: '#0369A1',
        sidebarActiveColor: '#E0F2FE',
        accentColor: '#38BDF8',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- DARK MODE SERIES (PREMIUM & DEEP) ---
    {
        id: 'obsidian-night',
        name: 'True Obsidian',
        category: 'Dark',
        primaryColor: '#FFFFFF',
        secondaryColor: '#E2E8F0',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#111111',
        accentColor: '#38BDF8',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#F43F5E',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'charcoal-pro',
        name: 'Charcoal Pro',
        category: 'Dark',
        primaryColor: '#F8FAFC',
        secondaryColor: '#CBD5E1',
        sidebarBackgroundColor: '#121212',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#1F1F1F',
        accentColor: '#10B981',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#D946EF',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'midnight-neon',
        name: 'Midnight Neon',
        category: 'Dark',
        primaryColor: '#A855F7',
        secondaryColor: '#D946EF',
        sidebarBackgroundColor: '#09090B',
        sidebarTextColor: '#A1A1AA',
        sidebarActiveColor: '#18181B',
        accentColor: '#FF00FF',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#A855F7',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'outer-space',
        name: 'Outer Space',
        category: 'Dark',
        primaryColor: '#60A5FA',
        secondaryColor: '#3B82F6',
        sidebarBackgroundColor: '#020617',
        sidebarTextColor: '#64748B',
        sidebarActiveColor: '#0F172A',
        accentColor: '#38BDF8',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dracula-clinical',
        name: 'Dracula Clinical',
        category: 'Dark',
        primaryColor: '#BD93F9',
        secondaryColor: '#FF79C6',
        sidebarBackgroundColor: '#282A36',
        sidebarTextColor: '#F8F8F2',
        sidebarActiveColor: '#44475A',
        accentColor: '#50FA7B',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- MEDICAL & CLINICAL ---
    {
        id: 'sterile-white',
        name: 'Sterile White',
        category: 'Classic',
        primaryColor: '#2563EB',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#334155',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#3B82F6',
        tertiaryColor: '#F97316',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'health-green',
        name: 'Health Green',
        category: 'Modern',
        primaryColor: '#059669',
        secondaryColor: '#047857',
        sidebarBackgroundColor: '#ECFDF5',
        sidebarTextColor: '#065F46',
        sidebarActiveColor: '#D1FAE5',
        accentColor: '#10B981',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emergency-red',
        name: 'Care Red',
        category: 'Special',
        primaryColor: '#DC2626',
        secondaryColor: '#B91C1C',
        sidebarBackgroundColor: '#FEF2F2',
        sidebarTextColor: '#991B1B',
        sidebarActiveColor: '#FEE2E2',
        accentColor: '#EF4444',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'teal-wellness',
        name: 'Teal Wellness',
        category: 'Modern',
        primaryColor: '#0D9488',
        secondaryColor: '#0F766E',
        sidebarBackgroundColor: '#115E59',
        sidebarTextColor: '#CCFBF1',
        sidebarActiveColor: '#14B8A6',
        accentColor: '#F59E0B',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },

    // --- VIBRANT & UNIQUE ---
    {
        id: 'magenta-premium',
        name: 'Magenta Premium',
        category: 'Special',
        primaryColor: '#D946EF',
        secondaryColor: '#C026D3',
        sidebarBackgroundColor: '#4A044E',
        sidebarTextColor: '#FAE8FF',
        sidebarActiveColor: '#701A75',
        accentColor: '#F472B6',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'violet-velvet',
        name: 'Violet Velvet',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#7C3AED',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#A78BFA',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#06B6D4',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'sunset-care',
        name: 'Sunset Care',
        category: 'Special',
        primaryColor: '#F97316',
        secondaryColor: '#EA580C',
        sidebarBackgroundColor: '#FFF7ED',
        sidebarTextColor: '#9A3412',
        sidebarActiveColor: '#FFEDD5',
        accentColor: '#FB923C',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#D946EF',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'earth-organic',
        name: 'Earth Organic',
        category: 'Classic',
        primaryColor: '#78350F',
        secondaryColor: '#92400E',
        sidebarBackgroundColor: '#FEF3C7',
        sidebarTextColor: '#451A03',
        sidebarActiveColor: '#FDE68A',
        accentColor: '#B45309',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'nordic-minimal',
        name: 'Nordic Minimal',
        category: 'Modern',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#F8FAFC',
        sidebarTextColor: '#475569',
        sidebarActiveColor: '#F1F5F9',
        accentColor: '#64748B',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'rose-gold-premium',
        name: 'Rose Gold',
        category: 'Special',
        primaryColor: '#BE123C',
        secondaryColor: '#E11D48',
        sidebarBackgroundColor: '#FFF1F2',
        sidebarTextColor: '#9F1239',
        sidebarActiveColor: '#FFE4E6',
        accentColor: '#FB7185',
        tertiaryColor: '#F97316',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emerald-luxury',
        name: 'Emerald Luxury',
        category: 'Classic',
        primaryColor: '#064E3B',
        secondaryColor: '#065F46',
        sidebarBackgroundColor: '#022C22',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#064E3B',
        accentColor: '#10B981',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#7C3AED',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'gold-obsidian',
        name: 'Gold Obsidian',
        category: 'Dark',
        primaryColor: '#EAB308',
        secondaryColor: '#CA8A04',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FEF9C3',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#FACC15',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#F43F5E',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'oceanic-breeze',
        name: 'Oceanic Breeze',
        category: 'Modern',
        primaryColor: '#0891B2',
        secondaryColor: '#0E7490',
        sidebarBackgroundColor: '#ECFEFF',
        sidebarTextColor: '#164E63',
        sidebarActiveColor: '#CFFAFE',
        accentColor: '#22D3EE',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'lavender-mist',
        name: 'Lavender Mist',
        category: 'Modern',
        primaryColor: '#7C3AED',
        secondaryColor: '#8B5CF6',
        sidebarBackgroundColor: '#F5F3FF',
        sidebarTextColor: '#5B21B6',
        sidebarActiveColor: '#EDE9FE',
        accentColor: '#A78BFA',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'carbon-fiber',
        name: 'Carbon Fiber',
        category: 'Dark',
        primaryColor: '#3F3F46',
        secondaryColor: '#27272A',
        sidebarBackgroundColor: '#18181B',
        sidebarTextColor: '#D4D4D8',
        sidebarActiveColor: '#27272A',
        accentColor: '#71717A',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'candy-clinical',
        name: 'Candy Clinical',
        category: 'Special',
        primaryColor: '#F43F5E',
        secondaryColor: '#E11D48',
        sidebarBackgroundColor: '#FFF1F2',
        sidebarTextColor: '#BE123C',
        sidebarActiveColor: '#FFE4E6',
        accentColor: '#FB7185',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'arctic-night',
        name: 'Arctic Night',
        category: 'Dark',
        primaryColor: '#BAE6FD',
        secondaryColor: '#7DD3FC',
        sidebarBackgroundColor: '#0C4A6E',
        sidebarTextColor: '#F0F9FF',
        sidebarActiveColor: '#075985',
        accentColor: '#38BDF8',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'deep-purple-premium',
        name: 'Deep Purple',
        category: 'Classic',
        primaryColor: '#4C1D95',
        secondaryColor: '#5B21B6',
        sidebarBackgroundColor: '#2E1065',
        sidebarTextColor: '#DDD6FE',
        sidebarActiveColor: '#4C1D95',
        accentColor: '#8B5CF6',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'forest-premium',
        name: 'Royal Forest',
        category: 'Classic',
        primaryColor: '#065F46',
        secondaryColor: '#064E3B',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#10B981',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#6366F1',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'slate-pro-dark',
        name: 'Slate Pro Dark',
        category: 'Dark',
        primaryColor: '#94A3B8',
        secondaryColor: '#64748B',
        sidebarBackgroundColor: '#0F172A',
        sidebarTextColor: '#F8FAFC',
        sidebarActiveColor: '#1E293B',
        accentColor: '#38BDF8',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'executive-classic-blue',
        name: 'Executive Classic',
        category: 'Classic',
        primaryColor: '#1D4ED8',
        secondaryColor: '#1E40AF',
        sidebarBackgroundColor: '#1E3A8A',
        sidebarTextColor: '#DBEAFE',
        sidebarActiveColor: '#2563EB',
        accentColor: '#3B82F6',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'luxury-gold',
        name: 'Pure Gold',
        category: 'Special',
        primaryColor: '#D4AF37',
        secondaryColor: '#B8860B',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#FFD700',
        sidebarActiveColor: '#1A1A1A',
        accentColor: '#FFD700',
        tertiaryColor: '#F97316',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'mint-clinical',
        name: 'Mint Clinical',
        category: 'Modern',
        primaryColor: '#10B981',
        secondaryColor: '#059669',
        sidebarBackgroundColor: '#F0FDF4',
        sidebarTextColor: '#166534',
        sidebarActiveColor: '#DCFCE7',
        accentColor: '#34D399',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'deep-charcoal',
        name: 'Deep Charcoal',
        category: 'Dark',
        primaryColor: '#F9FAFB',
        secondaryColor: '#F3F4F6',
        sidebarBackgroundColor: '#111827',
        sidebarTextColor: '#9CA3AF',
        sidebarActiveColor: '#1F2937',
        accentColor: '#3B82F6',
        tertiaryColor: '#FB923C',
        quaternaryColor: '#D946EF',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-glass',
        name: 'Glass Modern',
        category: 'Modern',
        primaryColor: '#000000',
        secondaryColor: '#333333',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#000000',
        sidebarActiveColor: '#F3F4F6',
        accentColor: '#000000',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'pacific-blue',
        name: 'Pacific Blue',
        category: 'Classic',
        primaryColor: '#0284C7',
        secondaryColor: '#0369A1',
        sidebarBackgroundColor: '#0C4A6E',
        sidebarTextColor: '#E0F2FE',
        sidebarActiveColor: '#075985',
        accentColor: '#38BDF8',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#A855F7',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- EMR INSPIRED SERIES ---
    {
        id: 'emr-hyperspace',
        name: 'Clinical Hyperspace',
        category: 'EMR',
        primaryColor: '#0072C6',
        secondaryColor: '#005A9E',
        sidebarBackgroundColor: '#F3F2F1',
        sidebarTextColor: '#323130',
        sidebarActiveColor: '#EDEBE9',
        accentColor: '#FF8C00',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-millennium',
        name: 'Clinical Millennium',
        category: 'EMR',
        primaryColor: '#1E914F',
        secondaryColor: '#166E3C',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#2D3748',
        sidebarActiveColor: '#F0FFF4',
        accentColor: '#3182CE',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-nextgen',
        name: 'Clinical NextGen',
        category: 'EMR',
        primaryColor: '#23527C',
        secondaryColor: '#1D4466',
        sidebarBackgroundColor: '#EDEDED',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#D9D9D9',
        accentColor: '#8C1D1D',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-athena',
        name: 'Clinical Athena',
        category: 'EMR',
        primaryColor: '#63666A',
        secondaryColor: '#4D4F53',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F4F4F4',
        accentColor: '#007BC3',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-allscripts',
        name: 'Clinical Allscripts',
        category: 'EMR',
        primaryColor: '#5D3F9B',
        secondaryColor: '#4A327C',
        sidebarBackgroundColor: '#002B49',
        sidebarTextColor: '#FFFFFF',
        sidebarActiveColor: '#003A63',
        accentColor: '#00A9E0',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-meditech',
        name: 'Clinical Meditech',
        category: 'EMR',
        primaryColor: '#005F7B',
        secondaryColor: '#004A60',
        sidebarBackgroundColor: '#F2F2F2',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E6E6E6',
        accentColor: '#D81B60',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-eclinical',
        name: 'Clinical eCW',
        category: 'EMR',
        primaryColor: '#008299',
        secondaryColor: '#006678',
        sidebarBackgroundColor: '#F7F9F9',
        sidebarTextColor: '#4D4D4D',
        sidebarActiveColor: '#E0E8E8',
        accentColor: '#F26522',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-trizetto',
        name: 'Clinical Trizetto',
        category: 'EMR',
        primaryColor: '#00A6CE',
        secondaryColor: '#0085A5',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#58595B',
        sidebarActiveColor: '#E6F6FA',
        accentColor: '#85C441',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-fusion',
        name: 'Clinical Fusion',
        category: 'EMR',
        primaryColor: '#417482',
        secondaryColor: '#345D68',
        sidebarBackgroundColor: '#F8F9F9',
        sidebarTextColor: '#2C3E50',
        sidebarActiveColor: '#ECF0F1',
        accentColor: '#E67E22',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-kareo',
        name: 'Clinical Kareo',
        category: 'EMR',
        primaryColor: '#00B4B0',
        secondaryColor: '#00908C',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#4A4A4A',
        sidebarActiveColor: '#F0FBFB',
        accentColor: '#F68B1F',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-mckesson',
        name: 'Clinical McKesson',
        category: 'EMR',
        primaryColor: '#003366',
        secondaryColor: '#002244',
        sidebarBackgroundColor: '#F0F0F0',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#D9D9D9',
        accentColor: '#FF6600',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-centricity',
        name: 'Clinical GE',
        category: 'EMR',
        primaryColor: '#005CB9',
        secondaryColor: '#004A95',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E6F2FF',
        accentColor: '#FDB913',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-greenway',
        name: 'Clinical Greenway',
        category: 'EMR',
        primaryColor: '#689F38',
        secondaryColor: '#558B2F',
        sidebarBackgroundColor: '#F1F8E9',
        sidebarTextColor: '#33691E',
        sidebarActiveColor: '#DCEDC8',
        accentColor: '#FFB300',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-modmed',
        name: 'Clinical ModMed',
        category: 'EMR',
        primaryColor: '#E67E22',
        secondaryColor: '#D35400',
        sidebarBackgroundColor: '#2C3E50',
        sidebarTextColor: '#ECF0F1',
        sidebarActiveColor: '#34495E',
        accentColor: '#1ABC9C',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-drchrono',
        name: 'Clinical drchrono',
        category: 'EMR',
        primaryColor: '#2C3E50',
        secondaryColor: '#1A252F',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#2C3E50',
        sidebarActiveColor: '#F4F6F6',
        accentColor: '#3498DB',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-advamd',
        name: 'Clinical AdvMD',
        category: 'EMR',
        primaryColor: '#0079C1',
        secondaryColor: '#00629B',
        sidebarBackgroundColor: '#F5F5F5',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E0E0E0',
        accentColor: '#FCAF17',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-elation',
        name: 'Clinical Elation',
        category: 'EMR',
        primaryColor: '#2A3F54',
        secondaryColor: '#1D2D3B',
        sidebarBackgroundColor: '#F7F7F7',
        sidebarTextColor: '#2A3F54',
        sidebarActiveColor: '#E9EDF2',
        accentColor: '#1ABB9C',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- MODERN CLINICAL SERIES ---
    {
        id: 'modern-mayo',
        name: 'Modern Rochester',
        category: 'Modern',
        primaryColor: '#00529B',
        secondaryColor: '#00407A',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F7FF',
        accentColor: '#00529B',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-cleveland',
        name: 'Modern Ohio',
        category: 'Modern',
        primaryColor: '#007A33',
        secondaryColor: '#006028',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0FFF4',
        accentColor: '#FFBC3D',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-hopkins',
        name: 'Modern Baltimore',
        category: 'Modern',
        primaryColor: '#002D72',
        secondaryColor: '#001D4A',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#FFC72C',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-stanford',
        name: 'Modern Palo Alto',
        category: 'Modern',
        primaryColor: '#8C1515',
        secondaryColor: '#6F1111',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FFF5F5',
        accentColor: '#007C92',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-massgen',
        name: 'Modern Boston',
        category: 'Modern',
        primaryColor: '#0072CE',
        secondaryColor: '#0059A1',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F8FF',
        accentColor: '#003A70',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-nyu',
        name: 'Modern Manhattan',
        category: 'Modern',
        primaryColor: '#57068C',
        secondaryColor: '#450570',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FAF5FF',
        accentColor: '#57068C',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-cedars',
        name: 'Modern Hollywood',
        category: 'Modern',
        primaryColor: '#C8102E',
        secondaryColor: '#A50D26',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FFF5F5',
        accentColor: '#C8102E',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-ucla',
        name: 'Modern Westwood',
        category: 'Modern',
        primaryColor: '#2774AE',
        secondaryColor: '#1E5B88',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F7FF',
        accentColor: '#FFD100',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-upenn',
        name: 'Modern Philly',
        category: 'Modern',
        primaryColor: '#011F5B',
        secondaryColor: '#00143D',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#990000',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-duke',
        name: 'Modern Durham',
        category: 'Modern',
        primaryColor: '#003087',
        secondaryColor: '#002569',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#003087',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-vanderbilt',
        name: 'Modern Nashville',
        category: 'Modern',
        primaryColor: '#1C1C1C',
        secondaryColor: '#000000',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F5F5F5',
        accentColor: '#866D4B',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-michigan',
        name: 'Modern Ann Arbor',
        category: 'Modern',
        primaryColor: '#00274C',
        secondaryColor: '#001C38',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#FFCB05',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-uw',
        name: 'Modern Seattle',
        category: 'Modern',
        primaryColor: '#4B2E83',
        secondaryColor: '#3A2466',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FAF5FF',
        accentColor: '#B7A57A',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-emory',
        name: 'Modern Atlanta',
        category: 'Modern',
        primaryColor: '#002878',
        secondaryColor: '#001E5A',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#D3A310',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-ucsf',
        name: 'Modern San Francisco',
        category: 'Modern',
        primaryColor: '#052049',
        secondaryColor: '#031530',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#18A3AC',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-northwestern',
        name: 'Modern Chicago',
        category: 'Modern',
        primaryColor: '#4E2A84',
        secondaryColor: '#3C2066',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FAF5FF',
        accentColor: '#4E2A84',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-mountsinai',
        name: 'Modern Sinai',
        category: 'Modern',
        primaryColor: '#EC008C',
        secondaryColor: '#C40074',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FFF5FA',
        accentColor: '#00AEEF',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-uchicago',
        name: 'Modern Phoenix',
        category: 'Modern',
        primaryColor: '#800000',
        secondaryColor: '#660000',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FFF5F5',
        accentColor: '#800000',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-yale',
        name: 'Modern New Haven',
        category: 'Modern',
        primaryColor: '#00356B',
        secondaryColor: '#00264D',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#63A6D8',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-cornell',
        name: 'Modern Ithaca',
        category: 'Modern',
        primaryColor: '#B31B1B',
        secondaryColor: '#8E1515',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#FFF5F5',
        accentColor: '#222222',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-columbia',
        name: 'Modern Upper Best',
        category: 'Modern',
        primaryColor: '#75BEE9',
        secondaryColor: '#5EA9D8',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F8FF',
        accentColor: '#1D4F91',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- CLASSIC SERIES (TIMELESS & STABLE) ---
    {
        id: 'classic-oxford',
        name: 'Classic Oxford',
        category: 'Classic',
        primaryColor: '#002147',
        secondaryColor: '#00152D',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#002147',
        sidebarActiveColor: '#F0F4F8',
        accentColor: '#002147',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'classic-cambridge',
        name: 'Classic Cambridge',
        category: 'Classic',
        primaryColor: '#A3C1AD',
        secondaryColor: '#86A792',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#003E33',
        sidebarActiveColor: '#EFF5F2',
        accentColor: '#003E33',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'classic-heritage',
        name: 'Heritage Oak',
        category: 'Classic',
        primaryColor: '#4A3728',
        secondaryColor: '#36281D',
        sidebarBackgroundColor: '#F9F7F2',
        sidebarTextColor: '#4A3728',
        sidebarActiveColor: '#F0EEE6',
        accentColor: '#4A3728',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- DARK SERIES (VOID & ECLIPSE) ---
    {
        id: 'dark-carbon',
        name: 'Carbon Dark',
        category: 'Dark',
        primaryColor: '#27272A',
        secondaryColor: '#18181B',
        sidebarBackgroundColor: '#09090B',
        sidebarTextColor: '#A1A1AA',
        sidebarActiveColor: '#18181B',
        accentColor: '#F4F4F5',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-onyx',
        name: 'Onyx Deep',
        category: 'Dark',
        primaryColor: '#0F172A',
        secondaryColor: '#020617',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#94A3B8',
        sidebarActiveColor: '#0F172A',
        accentColor: '#38BDF8',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- SPECIAL SERIES (AURORA & NEBULA) ---
    {
        id: 'special-aurora',
        name: 'Aurora Borealis',
        category: 'Special',
        primaryColor: '#10B981',
        secondaryColor: '#3B82F6',
        sidebarBackgroundColor: '#064E3B',
        sidebarTextColor: '#D1FAE5',
        sidebarActiveColor: '#065F46',
        accentColor: '#6366F1',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'special-nebula',
        name: 'Nebula Space',
        category: 'Special',
        primaryColor: '#8B5CF6',
        secondaryColor: '#EC4899',
        sidebarBackgroundColor: '#1E1B4B',
        sidebarTextColor: '#E0E7FF',
        sidebarActiveColor: '#312E81',
        accentColor: '#F43F5E',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#10B981',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    // --- MORE EMR CLASSICS ---
    {
        id: 'emr-medscape',
        name: 'Clinical Medscape',
        category: 'EMR',
        primaryColor: '#D32F2F',
        secondaryColor: '#B71C1C',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#212121',
        sidebarActiveColor: '#FFEBEE',
        accentColor: '#D32F2F',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-uptodate',
        name: 'Clinical UpToDate',
        category: 'EMR',
        primaryColor: '#005CB9',
        secondaryColor: '#004A95',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E6F2FF',
        accentColor: '#FDB913',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-tokyo',
        name: 'Modern Tokyo',
        category: 'Modern',
        primaryColor: '#FF0055',
        secondaryColor: '#CC0044',
        sidebarBackgroundColor: '#F8F9FA',
        sidebarTextColor: '#1A1A1B',
        sidebarActiveColor: '#FFE5EE',
        accentColor: '#00CCFF',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-seoul',
        name: 'Modern Seoul',
        category: 'Modern',
        primaryColor: '#0055FF',
        secondaryColor: '#0044CC',
        sidebarBackgroundColor: '#F8F9FA',
        sidebarTextColor: '#1A1A1B',
        sidebarActiveColor: '#E5EEFF',
        accentColor: '#FFCC00',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'classic-parchment',
        name: 'Classic Parchment',
        category: 'Classic',
        primaryColor: '#5D4037',
        secondaryColor: '#3E2723',
        sidebarBackgroundColor: '#F5F5DC',
        sidebarTextColor: '#5D4037',
        sidebarActiveColor: '#EEDC82',
        accentColor: '#795548',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-eclipse',
        name: 'Dark Eclipse',
        category: 'Dark',
        primaryColor: '#4A148C',
        secondaryColor: '#311B92',
        sidebarBackgroundColor: '#121212',
        sidebarTextColor: '#E1BEE7',
        sidebarActiveColor: '#4A148C',
        accentColor: '#FF4081',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'special-aurora-borealis',
        name: 'Aurora Night',
        category: 'Special',
        primaryColor: '#00E676',
        secondaryColor: '#00C853',
        sidebarBackgroundColor: '#1A237E',
        sidebarTextColor: '#E8EAF6',
        sidebarActiveColor: '#303F9F',
        accentColor: '#64FFDA',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'special-rainbow-care',
        name: 'Rainbow Clinical',
        category: 'Special',
        primaryColor: '#E91E63',
        secondaryColor: '#9C27B0',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#212121',
        sidebarActiveColor: '#FCE4EC',
        accentColor: '#FFEB3B',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-berlin',
        name: 'Modern Berlin',
        category: 'Modern',
        primaryColor: '#212121',
        secondaryColor: '#424242',
        sidebarBackgroundColor: '#EEEEEE',
        sidebarTextColor: '#212121',
        sidebarActiveColor: '#BDBDBD',
        accentColor: '#FFD600',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'classic-library',
        name: 'Classic Library',
        category: 'Classic',
        primaryColor: '#1B5E20',
        secondaryColor: '#004D40',
        sidebarBackgroundColor: '#EFEBE9',
        sidebarTextColor: '#1B5E20',
        sidebarActiveColor: '#D7CCC8',
        accentColor: '#FFD600',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-graphite',
        name: 'Graphite Pro',
        category: 'Dark',
        primaryColor: '#616161',
        secondaryColor: '#424242',
        sidebarBackgroundColor: '#212121',
        sidebarTextColor: '#F5F5F5',
        sidebarActiveColor: '#424242',
        accentColor: '#9E9E9E',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-webmd',
        name: 'Clinical WebMD',
        category: 'EMR',
        primaryColor: '#004A99',
        secondaryColor: '#003366',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E6F0F9',
        accentColor: '#004A99',
        tertiaryColor: '#FBBF24',
        quaternaryColor: '#3B82F6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-mayo-classic',
        name: 'Mayo Heritage',
        category: 'EMR',
        primaryColor: '#00529B',
        secondaryColor: '#003366',
        sidebarBackgroundColor: '#F5F5F5',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E0E0E0',
        accentColor: '#00529B',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-cleveland-classic',
        name: 'Cleveland Heritage',
        category: 'EMR',
        primaryColor: '#007A33',
        secondaryColor: '#005020',
        sidebarBackgroundColor: '#F5F5F5',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E0E0E0',
        accentColor: '#007A33',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-hopkins-classic',
        name: 'Hopkins Heritage',
        category: 'EMR',
        primaryColor: '#002D72',
        secondaryColor: '#001D4A',
        sidebarBackgroundColor: '#F5F5F5',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E0E0E0',
        accentColor: '#002D72',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'emr-athenahealth-classic',
        name: 'Athena Heritage',
        category: 'EMR',
        primaryColor: '#63666A',
        secondaryColor: '#4D4F53',
        sidebarBackgroundColor: '#F5F5F5',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#E0E0E0',
        accentColor: '#63666A',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-paris',
        name: 'Modern Paris',
        category: 'Modern',
        primaryColor: '#001735',
        secondaryColor: '#00264D',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#001735',
        sidebarActiveColor: '#F5F5F5',
        accentColor: '#C8B273',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'modern-london',
        name: 'Modern London',
        category: 'Modern',
        primaryColor: '#003087',
        secondaryColor: '#002569',
        sidebarBackgroundColor: '#FFFFFF',
        sidebarTextColor: '#333333',
        sidebarActiveColor: '#F0F4FF',
        accentColor: '#DA291C',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'classic-manuscript',
        name: 'Classic Manuscript',
        category: 'Classic',
        primaryColor: '#3E2723',
        secondaryColor: '#1B110D',
        sidebarBackgroundColor: '#FFF8E1',
        sidebarTextColor: '#3E2723',
        sidebarActiveColor: '#FFECB3',
        accentColor: '#3E2723',
        tertiaryColor: '#F59E0B',
        quaternaryColor: '#8B5CF6',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'dark-void',
        name: 'Void Space',
        category: 'Dark',
        primaryColor: '#000000',
        secondaryColor: '#121212',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#616161',
        sidebarActiveColor: '#121212',
        accentColor: '#FFFFFF',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    },
    {
        id: 'special-aurora-borealis-v2',
        name: 'Aurora Borealis II',
        category: 'Special',
        primaryColor: '#00E5FF',
        secondaryColor: '#00B8D4',
        sidebarBackgroundColor: '#000000',
        sidebarTextColor: '#E0F7FA',
        sidebarActiveColor: '#006064',
        accentColor: '#1DE9B6',
        tertiaryColor: '#FCD34D',
        quaternaryColor: '#EC4899',
        fontFamily: 'Inter, sans-serif',
        logoUrl: null,
        faviconUrl: null,
        orgNameOverride: null
    }
];
