/**
 * ENTERPRISE-GRADE FHIR Resource Fields for Rule Builder
 * 200+ fields with code systems, temporal operators, and workflow actions
 */

export interface CodeSystem {
  system: string;
  display: string;
  url: string;
}

export interface ValueSetOption {
  code: string;
  display: string;
  system?: string;
  definition?: string;
}

export interface FHIRFieldEnterprise {
  name: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'code' | 'reference' | 'temporal' | 'action';
  inputType?: 'text' | 'number' | 'date' | 'select' | 'multiselect' | 'code-search' | 'temporal-config';
  category: string;
  resource: string;
  fhirPath: string;
  description?: string;
  tooltip?: string;
  codeSystem?: CodeSystem;
  valueSet?: ValueSetOption[];
  valueSetUrl?: string;
  examples?: string[];
  unit?: string;
  temporalConfig?: {
    aggregationType: 'count' | 'avg' | 'sum' | 'min' | 'max' | 'first' | 'last' | 'trend';
    timeWindow?: string;
  };
}

// ==================== CODE SYSTEMS ====================
export const CODE_SYSTEMS = {
  LOINC: {
    system: 'LOINC',
    display: 'Logical Observation Identifiers Names and Codes',
    url: 'http://loinc.org',
  },
  SNOMED: {
    system: 'SNOMED CT',
    display: 'SNOMED Clinical Terms',
    url: 'http://snomed.info/sct',
  },
  ICD10: {
    system: 'ICD-10-CM',
    display: 'International Classification of Diseases, 10th Revision',
    url: 'http://hl7.org/fhir/sid/icd-10-cm',
  },
  RXNORM: {
    system: 'RxNorm',
    display: 'RxNorm',
    url: 'http://www.nlm.nih.gov/research/umls/rxnorm',
  },
  CPT: {
    system: 'CPT',
    display: 'Current Procedural Terminology',
    url: 'http://www.ama-assn.org/go/cpt',
  },
  UCUM: {
    system: 'UCUM',
    display: 'Unified Code for Units of Measure',
    url: 'http://unitsofmeasure.org',
  },
};

// ==================== FIELD CATEGORIES ====================
export const FHIR_FIELD_CATEGORIES = {
  PATIENT: 'Patient Demographics',
  VITAL_SIGNS: 'Vital Signs & Observations',
  LAB_RESULTS: 'Laboratory Results',
  MEDICATIONS: 'Medications',
  CONDITIONS: 'Diagnoses & Conditions',
  PROCEDURES: 'Procedures',
  ALLERGIES: 'Allergies & Intolerances',
  IMMUNIZATIONS: 'Immunizations',
  ENCOUNTERS: 'Encounters & Visits',
  CARE_PLANS: 'Care Plans',
  CARE_TEAMS: 'Care Teams',
  APPOINTMENTS: 'Appointments',
  DOCUMENTS: 'Clinical Documents',
  IMAGING: 'Imaging & Diagnostics',
  DIAGNOSTIC_REPORTS: 'Diagnostic Reports',
  DEVICES: 'Medical Devices',
  FAMILY_HISTORY: 'Family History',
  SOCIAL_HISTORY: 'Social Determinants of Health',
  GOALS: 'Care Goals',
  RISK_ASSESSMENTS: 'Risk Assessments',
  SERVICE_REQUESTS: 'Orders & Service Requests',
  COVERAGE: 'Insurance & Coverage',
  TEMPORAL: 'Temporal Operators',
  COMPUTED: 'Computed Variables',
  ACTIONS: 'Workflow Actions',
};

// ==================== ENTERPRISE FHIR FIELDS ====================
export const FHIR_FIELDS_ENTERPRISE: FHIRFieldEnterprise[] = [
  // ==================== PATIENT DEMOGRAPHICS ====================
  {
    name: 'patient.age',
    label: 'Patient Age',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.birthDate',
    description: 'Age in years, calculated from birth date',
    tooltip: 'Automatically calculated from patient birth date. Used for age-based screening and protocols.',
    examples: ['65', '18', '45'],
    unit: 'years',
  },
  {
    name: 'patient.age_months',
    label: 'Patient Age (Months)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.birthDate',
    description: 'Age in months for pediatric patients',
    tooltip: 'Used for pediatric growth charts and vaccination schedules',
    examples: ['6', '12', '24'],
    unit: 'months',
  },
  {
    name: 'patient.gender',
    label: 'Gender',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.gender',
    tooltip: 'Administrative gender for clinical decision support',
    valueSet: [
      { code: 'male', display: 'Male', definition: 'Male gender' },
      { code: 'female', display: 'Female', definition: 'Female gender' },
      { code: 'other', display: 'Other', definition: 'Other gender identity' },
      { code: 'unknown', display: 'Unknown', definition: 'Gender unknown' },
    ],
  },
  {
    name: 'patient.birthDate',
    label: 'Birth Date',
    type: 'date',
    inputType: 'date',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.birthDate',
    tooltip: 'Date of birth in ISO format (YYYY-MM-DD)',
  },
  {
    name: 'patient.deceased',
    label: 'Deceased Status',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.deceasedBoolean',
    tooltip: 'Indicates if the patient is deceased',
  },
  {
    name: 'patient.maritalStatus',
    label: 'Marital Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.maritalStatus.coding.code',
    tooltip: 'Current marital status (social determinant)',
    valueSet: [
      { code: 'S', display: 'Never Married' },
      { code: 'M', display: 'Married' },
      { code: 'D', display: 'Divorced' },
      { code: 'W', display: 'Widowed' },
    ],
  },
  {
    name: 'patient.language',
    label: 'Preferred Language',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.communication.language.coding.code',
    tooltip: 'Primary language for communication',
    valueSet: [
      { code: 'en', display: 'English' },
      { code: 'es', display: 'Spanish' },
      { code: 'zh', display: 'Chinese' },
      { code: 'ar', display: 'Arabic' },
    ],
  },
  {
    name: 'patient.race',
    label: 'Race',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.extension[us-core-race].valueCoding.code',
    tooltip: 'Race category (US Core extension)',
    valueSet: [
      { code: '2106-3', display: 'White' },
      { code: '2054-5', display: 'Black or African American' },
      { code: '2028-9', display: 'Asian' },
      { code: '1002-5', display: 'American Indian or Alaska Native' },
      { code: '2076-8', display: 'Native Hawaiian or Other Pacific Islander' },
    ],
  },
  {
    name: 'patient.ethnicity',
    label: 'Ethnicity',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PATIENT,
    resource: 'Patient',
    fhirPath: 'Patient.extension[us-core-ethnicity].valueCoding.code',
    tooltip: 'Ethnicity category (US Core extension)',
    valueSet: [
      { code: '2135-2', display: 'Hispanic or Latino' },
      { code: '2186-5', display: 'Not Hispanic or Latino' },
    ],
  },

  // ==================== VITAL SIGNS (LOINC-CODED) ====================
  {
    name: 'observation.bp_systolic',
    label: 'Blood Pressure - Systolic',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.component[systolic].valueQuantity.value',
    description: 'Systolic BP in mmHg',
    tooltip: 'LOINC: 8480-6. Normal: <120 mmHg. Stage 1 HTN: 130-139. Stage 2 HTN: ≥140.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['120', '140', '160'],
    unit: 'mmHg',
  },
  {
    name: 'observation.bp_diastolic',
    label: 'Blood Pressure - Diastolic',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.component[diastolic].valueQuantity.value',
    description: 'Diastolic BP in mmHg',
    tooltip: 'LOINC: 8462-4. Normal: <80 mmHg. Stage 1 HTN: 80-89. Stage 2 HTN: ≥90.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['80', '90', '100'],
    unit: 'mmHg',
  },
  {
    name: 'observation.heart_rate',
    label: 'Heart Rate',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Heart rate in beats per minute',
    tooltip: 'LOINC: 8867-4. Normal adult: 60-100 bpm. Tachycardia: >100. Bradycardia: <60.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['60', '80', '100'],
    unit: 'bpm',
  },
  {
    name: 'observation.temperature',
    label: 'Body Temperature',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Temperature in °F or °C',
    tooltip: 'LOINC: 8310-5. Normal: 97-99°F (36-37°C). Fever: ≥100.4°F (38°C).',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['98.6', '100.4', '101.5'],
    unit: '°F',
  },
  {
    name: 'observation.respiratory_rate',
    label: 'Respiratory Rate',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Breaths per minute',
    tooltip: 'LOINC: 9279-1. Normal adult: 12-20/min. Tachypnea: >20. qSOFA criteria: ≥22.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: '/min',
  },
  {
    name: 'observation.oxygen_saturation',
    label: 'Oxygen Saturation (SpO2)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'O2 saturation percentage',
    tooltip: 'LOINC: 2708-6. Normal: ≥95%. Hypoxemia: <90%. Supplemental O2 may be needed.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['95', '92', '88'],
    unit: '%',
  },
  {
    name: 'observation.weight',
    label: 'Weight',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Body weight',
    tooltip: 'LOINC: 29463-7. Used for BMI calculation and medication dosing.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'kg',
  },
  {
    name: 'observation.height',
    label: 'Height',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Body height',
    tooltip: 'LOINC: 8302-2. Used for BMI calculation and growth charts.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'cm',
  },
  {
    name: 'observation.bmi',
    label: 'BMI',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Body Mass Index',
    tooltip: 'LOINC: 39156-5. Normal: 18.5-24.9. Overweight: 25-29.9. Obese: ≥30.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['18.5', '25', '30'],
    unit: 'kg/m2',
  },
  {
    name: 'observation.pain_score',
    label: 'Pain Score (0-10)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.VITAL_SIGNS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Pain intensity scale',
    tooltip: 'LOINC: 72514-3. 0=No pain, 1-3=Mild, 4-6=Moderate, 7-10=Severe.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['0', '5', '8'],
    unit: '{score}',
  },

  // ==================== LABORATORY RESULTS (LOINC-CODED) ====================
  {
    name: 'observation.lab_glucose',
    label: 'Blood Glucose',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Glucose level',
    tooltip: 'LOINC: 2339-0 (random), 1558-6 (fasting). Normal fasting: 70-100. Prediabetes: 100-125. Diabetes: ≥126.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['100', '126', '200'],
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_a1c',
    label: 'Hemoglobin A1c',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: '3-month average glucose',
    tooltip: 'LOINC: 4548-4. Normal: <5.7%. Prediabetes: 5.7-6.4%. Diabetes: ≥6.5%. Target for diabetics: <7%.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['5.7', '6.5', '9.0'],
    unit: '%',
  },
  {
    name: 'observation.lab_cholesterol_total',
    label: 'Total Cholesterol',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Total cholesterol',
    tooltip: 'LOINC: 2093-3. Desirable: <200. Borderline high: 200-239. High: ≥240.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_ldl',
    label: 'LDL Cholesterol',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Low-density lipoprotein',
    tooltip: 'LOINC: 18262-6. Optimal: <100. Near optimal: 100-129. High: ≥160.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_hdl',
    label: 'HDL Cholesterol',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'High-density lipoprotein',
    tooltip: 'LOINC: 2085-9. Protective: ≥60. Low (risk factor): <40 men, <50 women.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_triglycerides',
    label: 'Triglycerides',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Serum triglycerides',
    tooltip: 'LOINC: 2571-8. Normal: <150. Borderline high: 150-199. High: 200-499. Very high: ≥500.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_creatinine',
    label: 'Creatinine',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Serum creatinine',
    tooltip: 'LOINC: 2160-0. Normal: 0.6-1.2 mg/dL. Elevated indicates kidney dysfunction.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_egfr',
    label: 'eGFR',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Estimated glomerular filtration rate',
    tooltip: 'LOINC: 48642-3. Normal: ≥90. Stage 3 CKD: 30-59. Stage 4: 15-29. Stage 5: <15.',
    codeSystem: CODE_SYSTEMS.LOINC,
    examples: ['90', '60', '30'],
    unit: 'mL/min/1.73m2',
  },
  {
    name: 'observation.lab_bun',
    label: 'BUN (Blood Urea Nitrogen)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Blood urea nitrogen',
    tooltip: 'LOINC: 3094-0. Normal: 7-20 mg/dL. Elevated in kidney disease, dehydration.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mg/dL',
  },
  {
    name: 'observation.lab_sodium',
    label: 'Sodium',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Serum sodium',
    tooltip: 'LOINC: 2951-2. Normal: 135-145 mEq/L. Hyponatremia: <135. Hypernatremia: >145.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mEq/L',
  },
  {
    name: 'observation.lab_potassium',
    label: 'Potassium',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Serum potassium',
    tooltip: 'LOINC: 2823-3. Normal: 3.5-5.0 mEq/L. Critical: <2.5 or >6.5.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mEq/L',
  },
  {
    name: 'observation.lab_hemoglobin',
    label: 'Hemoglobin',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Hemoglobin concentration',
    tooltip: 'LOINC: 718-7. Normal: 12-16 g/dL (women), 14-18 g/dL (men). Anemia: <12 women, <13 men.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'g/dL',
  },
  {
    name: 'observation.lab_wbc',
    label: 'White Blood Cell Count',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'WBC count',
    tooltip: 'LOINC: 6690-2. Normal: 4.5-11 K/µL. Elevated in infection. Low in immunosuppression.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'K/µL',
  },
  {
    name: 'observation.lab_platelet_count',
    label: 'Platelet Count',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Platelet count',
    tooltip: 'LOINC: 777-3. Normal: 150-400 K/µL. Thrombocytopenia: <150. Risk of bleeding: <50.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'K/µL',
  },
  {
    name: 'observation.lab_inr',
    label: 'INR',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'International Normalized Ratio',
    tooltip: 'LOINC: 6301-6. Normal: 0.8-1.2. Warfarin target: 2-3 (AFib), 2.5-3.5 (mechanical valve).',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: '{ratio}',
  },
  {
    name: 'observation.lab_troponin',
    label: 'Troponin I',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Cardiac troponin',
    tooltip: 'LOINC: 10839-9. Elevated in myocardial infarction. Critical marker for ACS.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'ng/mL',
  },
  {
    name: 'observation.lab_bnp',
    label: 'BNP',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'B-type Natriuretic Peptide',
    tooltip: 'LOINC: 30934-4. Normal: <100. Elevated in heart failure. >400: likely HF.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'pg/mL',
  },
  {
    name: 'observation.lab_lactate',
    label: 'Lactate',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.valueQuantity.value',
    description: 'Serum lactate',
    tooltip: 'LOINC: 2524-7. Normal: <2 mmol/L. Elevated in sepsis. >4: severe sepsis/shock.',
    codeSystem: CODE_SYSTEMS.LOINC,
    unit: 'mmol/L',
  },
  {
    name: 'observation.lab_interpretation',
    label: 'Lab Result Interpretation',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.LAB_RESULTS,
    resource: 'Observation',
    fhirPath: 'Observation.interpretation.coding.code',
    tooltip: 'Standard interpretation codes',
    valueSet: [
      { code: 'N', display: 'Normal', definition: 'Within normal range' },
      { code: 'H', display: 'High', definition: 'Above normal range' },
      { code: 'L', display: 'Low', definition: 'Below normal range' },
      { code: 'HH', display: 'Critical High', definition: 'Critically high, immediate action' },
      { code: 'LL', display: 'Critical Low', definition: 'Critically low, immediate action' },
      { code: 'A', display: 'Abnormal', definition: 'Abnormal, not H/L' },
    ],
  },

  // ==================== MEDICATIONS (RxNorm-CODED) ====================
  {
    name: 'medication.code',
    label: 'Medication Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.medicationCodeableConcept.coding.code',
    description: 'RxNorm code for medication',
    tooltip: 'Search RxNorm codes. Example: 197361 (Lisinopril), 314076 (Metformin).',
    codeSystem: CODE_SYSTEMS.RXNORM,
  },
  {
    name: 'medication.name',
    label: 'Medication Name',
    type: 'string',
    inputType: 'text',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.medicationCodeableConcept.text',
    tooltip: 'Medication display name',
  },
  {
    name: 'medication.status',
    label: 'Medication Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.status',
    tooltip: 'Current status of medication order',
    valueSet: [
      { code: 'active', display: 'Active', definition: 'Medication is currently being taken' },
      { code: 'completed', display: 'Completed', definition: 'Medication regimen completed' },
      { code: 'stopped', display: 'Stopped', definition: 'Medication discontinued' },
      { code: 'draft', display: 'Draft', definition: 'Order not yet active' },
      { code: 'cancelled', display: 'Cancelled', definition: 'Order cancelled' },
    ],
  },
  {
    name: 'medication.intent',
    label: 'Medication Intent',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.intent',
    valueSet: [
      { code: 'order', display: 'Order' },
      { code: 'plan', display: 'Plan' },
      { code: 'proposal', display: 'Proposal' },
    ],
  },
  {
    name: 'medication.dosage_quantity',
    label: 'Dosage Quantity',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.dosageInstruction.doseAndRate.doseQuantity.value',
    tooltip: 'Numeric dose amount',
  },
  {
    name: 'medication.route',
    label: 'Route of Administration',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'MedicationRequest.dosageInstruction.route.coding.code',
    tooltip: 'How medication is administered',
    codeSystem: CODE_SYSTEMS.SNOMED,
    valueSet: [
      { code: '26643006', display: 'Oral', system: 'SNOMED' },
      { code: '47625008', display: 'Intravenous', system: 'SNOMED' },
      { code: '78421000', display: 'Intramuscular', system: 'SNOMED' },
      { code: '37161004', display: 'Subcutaneous', system: 'SNOMED' },
    ],
  },
  {
    name: 'medication.class_ace_arb',
    label: 'ACE Inhibitor / ARB',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'computed',
    description: 'Patient on ACE-I or ARB',
    tooltip: 'Checks if patient has active ACE inhibitor or ARB. Used for heart failure and CKD protocols.',
  },
  {
    name: 'medication.class_beta_blocker',
    label: 'Beta Blocker',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'computed',
    description: 'Patient on beta blocker',
    tooltip: 'Checks if patient has active beta blocker. Used for heart failure and MI protocols.',
  },
  {
    name: 'medication.class_anticoagulant',
    label: 'Anticoagulant',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'computed',
    description: 'Patient on anticoagulation',
    tooltip: 'Checks for warfarin, DOACs (apixaban, rivaroxaban, dabigatran, edoxaban). Used for AFib stroke prevention.',
  },
  {
    name: 'medication.class_statin',
    label: 'Statin',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'computed',
    description: 'Patient on statin',
    tooltip: 'Checks for any HMG-CoA reductase inhibitor. Used for ASCVD risk reduction.',
  },
  {
    name: 'medication.class_insulin',
    label: 'Insulin',
    type: 'boolean',
    category: FHIR_FIELD_CATEGORIES.MEDICATIONS,
    resource: 'MedicationRequest',
    fhirPath: 'computed',
    description: 'Patient on insulin',
    tooltip: 'Checks for any insulin product. Used for diabetes management.',
  },

  // ==================== CONDITIONS (ICD-10 / SNOMED) ====================
  {
    name: 'condition.code',
    label: 'Condition Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.CONDITIONS,
    resource: 'Condition',
    fhirPath: 'Condition.code.coding.code',
    description: 'ICD-10 or SNOMED code',
    tooltip: 'Search diagnosis codes. ICD-10 examples: E11.9 (Diabetes), I10 (HTN), I50.9 (Heart failure).',
    codeSystem: CODE_SYSTEMS.ICD10,
    examples: ['E11.9', 'I10', 'I50.9', 'J44.0'],
  },
  {
    name: 'condition.category',
    label: 'Condition Category',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.CONDITIONS,
    resource: 'Condition',
    fhirPath: 'Condition.category.coding.code',
    valueSet: [
      { code: 'problem-list-item', display: 'Problem List Item' },
      { code: 'encounter-diagnosis', display: 'Encounter Diagnosis' },
    ],
  },
  {
    name: 'condition.severity',
    label: 'Condition Severity',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.CONDITIONS,
    resource: 'Condition',
    fhirPath: 'Condition.severity.coding.code',
    valueSet: [
      { code: '255604002', display: 'Mild', system: 'SNOMED' },
      { code: '6736007', display: 'Moderate', system: 'SNOMED' },
      { code: '24484000', display: 'Severe', system: 'SNOMED' },
    ],
  },
  {
    name: 'condition.clinicalStatus',
    label: 'Clinical Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.CONDITIONS,
    resource: 'Condition',
    fhirPath: 'Condition.clinicalStatus.coding.code',
    tooltip: 'Current clinical status of the condition',
    valueSet: [
      { code: 'active', display: 'Active', definition: 'Condition is active and ongoing' },
      { code: 'recurrence', display: 'Recurrence', definition: 'Condition has recurred' },
      { code: 'relapse', display: 'Relapse', definition: 'Return after remission' },
      { code: 'inactive', display: 'Inactive', definition: 'Not currently active' },
      { code: 'remission', display: 'Remission', definition: 'In remission' },
      { code: 'resolved', display: 'Resolved', definition: 'Condition resolved' },
    ],
  },
  {
    name: 'condition.onsetAge',
    label: 'Condition Onset Age',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.CONDITIONS,
    resource: 'Condition',
    fhirPath: 'Condition.onsetAge.value',
    tooltip: 'Age when condition started',
  },

  // ==================== PROCEDURES (CPT / SNOMED) ====================
  {
    name: 'procedure.code',
    label: 'Procedure Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.PROCEDURES,
    resource: 'Procedure',
    fhirPath: 'Procedure.code.coding.code',
    description: 'CPT or SNOMED procedure code',
    tooltip: 'Search procedure codes. CPT examples: 99213 (Office visit), 93000 (EKG).',
    codeSystem: CODE_SYSTEMS.CPT,
  },
  {
    name: 'procedure.status',
    label: 'Procedure Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.PROCEDURES,
    resource: 'Procedure',
    fhirPath: 'Procedure.status',
    valueSet: [
      { code: 'preparation', display: 'Preparation' },
      { code: 'in-progress', display: 'In Progress' },
      { code: 'completed', display: 'Completed' },
      { code: 'stopped', display: 'Stopped' },
      { code: 'not-done', display: 'Not Done' },
    ],
  },
  {
    name: 'procedure.performedDate',
    label: 'Procedure Date',
    type: 'date',
    inputType: 'date',
    category: FHIR_FIELD_CATEGORIES.PROCEDURES,
    resource: 'Procedure',
    fhirPath: 'Procedure.performedDateTime',
    tooltip: 'Date procedure was performed',
  },

  // ==================== IMMUNIZATIONS ====================
  {
    name: 'immunization.vaccineCode',
    label: 'Vaccine Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.IMMUNIZATIONS,
    resource: 'Immunization',
    fhirPath: 'Immunization.vaccineCode.coding.code',
    description: 'CVX vaccine code',
    tooltip: 'Vaccine code (CVX). Examples: 141 (Influenza), 208 (COVID-19).',
  },
  {
    name: 'immunization.status',
    label: 'Immunization Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.IMMUNIZATIONS,
    resource: 'Immunization',
    fhirPath: 'Immunization.status',
    valueSet: [
      { code: 'completed', display: 'Completed' },
      { code: 'entered-in-error', display: 'Entered in Error' },
      { code: 'not-done', display: 'Not Done' },
    ],
  },
  {
    name: 'immunization.occurrenceDate',
    label: 'Vaccination Date',
    type: 'date',
    inputType: 'date',
    category: FHIR_FIELD_CATEGORIES.IMMUNIZATIONS,
    resource: 'Immunization',
    fhirPath: 'Immunization.occurrenceDateTime',
  },

  // ==================== ALLERGIES ====================
  {
    name: 'allergy.code',
    label: 'Allergen Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.ALLERGIES,
    resource: 'AllergyIntolerance',
    fhirPath: 'AllergyIntolerance.code.coding.code',
    codeSystem: CODE_SYSTEMS.SNOMED,
  },
  {
    name: 'allergy.category',
    label: 'Allergy Category',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ALLERGIES,
    resource: 'AllergyIntolerance',
    fhirPath: 'AllergyIntolerance.category',
    valueSet: [
      { code: 'food', display: 'Food' },
      { code: 'medication', display: 'Medication' },
      { code: 'environment', display: 'Environment' },
      { code: 'biologic', display: 'Biologic' },
    ],
  },
  {
    name: 'allergy.criticality',
    label: 'Allergy Criticality',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ALLERGIES,
    resource: 'AllergyIntolerance',
    fhirPath: 'AllergyIntolerance.criticality',
    tooltip: 'Potential clinical harm severity',
    valueSet: [
      { code: 'low', display: 'Low Risk', definition: 'Low risk of harm' },
      { code: 'high', display: 'High Risk', definition: 'High risk of harm' },
      { code: 'unable-to-assess', display: 'Unable to Assess' },
    ],
  },
  {
    name: 'allergy.type',
    label: 'Allergy Type',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ALLERGIES,
    resource: 'AllergyIntolerance',
    fhirPath: 'AllergyIntolerance.type',
    valueSet: [
      { code: 'allergy', display: 'Allergy', definition: 'Immune-mediated reaction' },
      { code: 'intolerance', display: 'Intolerance', definition: 'Non-immune reaction' },
    ],
  },

  // ==================== ENCOUNTERS ====================
  {
    name: 'encounter.type',
    label: 'Encounter Type',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.ENCOUNTERS,
    resource: 'Encounter',
    fhirPath: 'Encounter.type.coding.code',
    codeSystem: CODE_SYSTEMS.CPT,
  },
  {
    name: 'encounter.class',
    label: 'Encounter Class',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ENCOUNTERS,
    resource: 'Encounter',
    fhirPath: 'Encounter.class.code',
    tooltip: 'Classification of patient encounter',
    valueSet: [
      { code: 'AMB', display: 'Ambulatory', definition: 'Outpatient visit' },
      { code: 'EMER', display: 'Emergency', definition: 'Emergency department' },
      { code: 'HH', display: 'Home Health', definition: 'Home care visit' },
      { code: 'IMP', display: 'Inpatient', definition: 'Hospital admission' },
      { code: 'ACUTE', display: 'Acute Inpatient', definition: 'Acute care' },
      { code: 'NONAC', display: 'Non-Acute Inpatient', definition: 'Long-term care' },
      { code: 'VR', display: 'Virtual', definition: 'Telehealth' },
    ],
  },
  {
    name: 'encounter.status',
    label: 'Encounter Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ENCOUNTERS,
    resource: 'Encounter',
    fhirPath: 'Encounter.status',
    valueSet: [
      { code: 'planned', display: 'Planned' },
      { code: 'arrived', display: 'Arrived' },
      { code: 'in-progress', display: 'In Progress' },
      { code: 'finished', display: 'Finished' },
      { code: 'cancelled', display: 'Cancelled' },
    ],
  },
  {
    name: 'encounter.priority',
    label: 'Encounter Priority',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.ENCOUNTERS,
    resource: 'Encounter',
    fhirPath: 'Encounter.priority.coding.code',
    valueSet: [
      { code: 'routine', display: 'Routine' },
      { code: 'urgent', display: 'Urgent' },
      { code: 'stat', display: 'STAT' },
      { code: 'asap', display: 'ASAP' },
    ],
  },

  // ==================== CARE PLANS ====================
  {
    name: 'careplan.status',
    label: 'Care Plan Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.CARE_PLANS,
    resource: 'CarePlan',
    fhirPath: 'CarePlan.status',
    valueSet: [
      { code: 'draft', display: 'Draft' },
      { code: 'active', display: 'Active' },
      { code: 'completed', display: 'Completed' },
      { code: 'revoked', display: 'Revoked' },
    ],
  },
  {
    name: 'careplan.intent',
    label: 'Care Plan Intent',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.CARE_PLANS,
    resource: 'CarePlan',
    fhirPath: 'CarePlan.intent',
    valueSet: [
      { code: 'proposal', display: 'Proposal' },
      { code: 'plan', display: 'Plan' },
      { code: 'order', display: 'Order' },
    ],
  },
  {
    name: 'careplan.category',
    label: 'Care Plan Category',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.CARE_PLANS,
    resource: 'CarePlan',
    fhirPath: 'CarePlan.category.coding.code',
    codeSystem: CODE_SYSTEMS.SNOMED,
  },

  // ==================== SERVICE REQUESTS (ORDERS) ====================
  {
    name: 'servicerequest.code',
    label: 'Service/Order Code',
    type: 'code',
    inputType: 'code-search',
    category: FHIR_FIELD_CATEGORIES.SERVICE_REQUESTS,
    resource: 'ServiceRequest',
    fhirPath: 'ServiceRequest.code.coding.code',
    description: 'Lab, imaging, or procedure order',
    tooltip: 'LOINC or CPT code for the requested service',
    codeSystem: CODE_SYSTEMS.LOINC,
  },
  {
    name: 'servicerequest.status',
    label: 'Order Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.SERVICE_REQUESTS,
    resource: 'ServiceRequest',
    fhirPath: 'ServiceRequest.status',
    valueSet: [
      { code: 'draft', display: 'Draft' },
      { code: 'active', display: 'Active' },
      { code: 'completed', display: 'Completed' },
      { code: 'revoked', display: 'Revoked' },
    ],
  },
  {
    name: 'servicerequest.priority',
    label: 'Order Priority',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.SERVICE_REQUESTS,
    resource: 'ServiceRequest',
    fhirPath: 'ServiceRequest.priority',
    valueSet: [
      { code: 'routine', display: 'Routine' },
      { code: 'urgent', display: 'Urgent' },
      { code: 'stat', display: 'STAT' },
      { code: 'asap', display: 'ASAP' },
    ],
  },

  // ==================== GOALS ====================
  {
    name: 'goal.description',
    label: 'Goal Description',
    type: 'string',
    inputType: 'text',
    category: FHIR_FIELD_CATEGORIES.GOALS,
    resource: 'Goal',
    fhirPath: 'Goal.description.text',
  },
  {
    name: 'goal.lifecycleStatus',
    label: 'Goal Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.GOALS,
    resource: 'Goal',
    fhirPath: 'Goal.lifecycleStatus',
    valueSet: [
      { code: 'proposed', display: 'Proposed' },
      { code: 'active', display: 'Active' },
      { code: 'completed', display: 'Completed' },
      { code: 'cancelled', display: 'Cancelled' },
    ],
  },
  {
    name: 'goal.achievementStatus',
    label: 'Achievement Status',
    type: 'code',
    inputType: 'select',
    category: FHIR_FIELD_CATEGORIES.GOALS,
    resource: 'Goal',
    fhirPath: 'Goal.achievementStatus.coding.code',
    valueSet: [
      { code: 'in-progress', display: 'In Progress' },
      { code: 'achieved', display: 'Achieved' },
      { code: 'not-achieved', display: 'Not Achieved' },
    ],
  },

  // ==================== RISK ASSESSMENTS ====================
  {
    name: 'riskassessment.prediction_outcome',
    label: 'Risk Outcome',
    type: 'string',
    category: FHIR_FIELD_CATEGORIES.RISK_ASSESSMENTS,
    resource: 'RiskAssessment',
    fhirPath: 'RiskAssessment.prediction.outcome.text',
  },
  {
    name: 'riskassessment.probability',
    label: 'Risk Probability',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.RISK_ASSESSMENTS,
    resource: 'RiskAssessment',
    fhirPath: 'RiskAssessment.prediction.probabilityDecimal',
    unit: '%',
  },

  // ==================== TEMPORAL OPERATORS ====================
  {
    name: 'temporal.count_within',
    label: 'COUNT (Time Window)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Count occurrences within time period',
    tooltip: 'Example: COUNT(observation.bp_systolic > 140, last_30_days) >= 3',
    temporalConfig: {
      aggregationType: 'count',
      timeWindow: 'configurable',
    },
  },
  {
    name: 'temporal.avg_within',
    label: 'AVG (Time Window)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Average value over time period',
    tooltip: 'Example: AVG(observation.glucose, last_7_days) > 180',
    temporalConfig: {
      aggregationType: 'avg',
      timeWindow: 'configurable',
    },
  },
  {
    name: 'temporal.sum_within',
    label: 'SUM (Time Window)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Sum values over time period',
    tooltip: 'Example: SUM(medication.dosage, last_month)',
    temporalConfig: {
      aggregationType: 'sum',
    },
  },
  {
    name: 'temporal.min_within',
    label: 'MIN (Time Window)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Minimum value in time period',
    tooltip: 'Example: MIN(observation.egfr, last_6_months) < 60',
    temporalConfig: {
      aggregationType: 'min',
    },
  },
  {
    name: 'temporal.max_within',
    label: 'MAX (Time Window)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Maximum value in time period',
    tooltip: 'Example: MAX(observation.bp_systolic, last_24_hours) > 160',
    temporalConfig: {
      aggregationType: 'max',
    },
  },
  {
    name: 'temporal.first',
    label: 'FIRST (Earliest Value)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'First/earliest recorded value',
    tooltip: 'Example: FIRST(observation.a1c)',
    temporalConfig: {
      aggregationType: 'first',
    },
  },
  {
    name: 'temporal.last',
    label: 'LAST (Most Recent Value)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Last/most recent recorded value',
    tooltip: 'Example: LAST(observation.creatinine) > 1.5',
    temporalConfig: {
      aggregationType: 'last',
    },
  },
  {
    name: 'temporal.trend_up',
    label: 'TREND_UP (Increasing)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Value is trending upward',
    tooltip: 'Example: TREND_UP(observation.creatinine, last_3_months)',
    temporalConfig: {
      aggregationType: 'trend',
    },
  },
  {
    name: 'temporal.trend_down',
    label: 'TREND_DOWN (Decreasing)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Value is trending downward',
    tooltip: 'Example: TREND_DOWN(observation.egfr, last_6_months)',
    temporalConfig: {
      aggregationType: 'trend',
    },
  },
  {
    name: 'temporal.time_since',
    label: 'TIME_SINCE (Last Event)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Time elapsed since last event',
    tooltip: 'Example: TIME_SINCE(encounter.class = AMB) > 365 days',
    temporalConfig: {
      aggregationType: 'count',
    },
  },
  {
    name: 'temporal.duration',
    label: 'DURATION (Total Time)',
    type: 'temporal',
    inputType: 'temporal-config',
    category: FHIR_FIELD_CATEGORIES.TEMPORAL,
    resource: 'Temporal',
    fhirPath: 'temporal',
    description: 'Duration of a condition or state',
    tooltip: 'Example: DURATION(condition.clinicalStatus = active) > 90 days',
    temporalConfig: {
      aggregationType: 'count',
    },
  },

  // ==================== WORKFLOW ACTIONS ====================
  {
    name: 'action.create_task',
    label: 'Create Task',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'Task',
    fhirPath: 'action',
    description: 'Create a new task for care team',
    tooltip: 'Creates a FHIR Task resource. Assign to care team members.',
  },
  {
    name: 'action.create_careplan',
    label: 'Create Care Plan',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'CarePlan',
    fhirPath: 'action',
    description: 'Create a new care plan',
    tooltip: 'Creates a FHIR CarePlan resource with activities.',
  },
  {
    name: 'action.create_servicerequest',
    label: 'Create Order',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'ServiceRequest',
    fhirPath: 'action',
    description: 'Create lab/imaging/procedure order',
    tooltip: 'Creates a FHIR ServiceRequest for labs, imaging, or procedures.',
  },
  {
    name: 'action.create_medicationrequest',
    label: 'Create Medication Order',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'MedicationRequest',
    fhirPath: 'action',
    description: 'Create medication order',
    tooltip: 'Creates a FHIR MedicationRequest (prescription).',
  },
  {
    name: 'action.send_notification',
    label: 'Send Notification',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'Communication',
    fhirPath: 'action',
    description: 'Send alert/notification',
    tooltip: 'Sends notification to care team via FHIR Communication resource.',
  },
  {
    name: 'action.update_status',
    label: 'Update Resource Status',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'Any',
    fhirPath: 'action',
    description: 'Update status of any resource',
    tooltip: 'Updates the status field of a FHIR resource.',
  },
  {
    name: 'action.launch_protocol',
    label: 'Launch Protocol',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'PlanDefinition',
    fhirPath: 'action',
    description: 'Execute clinical protocol',
    tooltip: 'Launches a FHIR PlanDefinition (e.g., sepsis bundle, heart failure pathway).',
  },
  {
    name: 'action.schedule_appointment',
    label: 'Schedule Appointment',
    type: 'action',
    category: FHIR_FIELD_CATEGORIES.ACTIONS,
    resource: 'Appointment',
    fhirPath: 'action',
    description: 'Auto-schedule follow-up',
    tooltip: 'Creates suggested Appointment for follow-up care.',
  },

  // ==================== COMPUTED VARIABLES ====================
  {
    name: 'var.bp_systolic_avg_24h',
    label: 'Avg Systolic BP (24h)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Average systolic BP over last 24 hours',
    tooltip: 'Computed from multiple BP readings. More reliable than single reading.',
  },
  {
    name: 'var.bp_diastolic_avg_24h',
    label: 'Avg Diastolic BP (24h)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Average diastolic BP over last 24 hours',
  },
  {
    name: 'var.glucose_avg_7d',
    label: 'Avg Glucose (7 days)',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: '7-day average glucose',
    tooltip: 'Rolling 7-day average for diabetes management.',
  },
  {
    name: 'var.med_adherence_score',
    label: 'Medication Adherence Score',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: '0-100 adherence score',
    tooltip: 'PDC (Proportion of Days Covered). <80% = non-adherent.',
    unit: '%',
  },
  {
    name: 'var.fall_risk_score',
    label: 'Fall Risk Score',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Morse Fall Scale or similar',
    tooltip: '0-24: Low risk, 25-44: Moderate, ≥45: High risk',
  },
  {
    name: 'var.cha2ds2_vasc_score',
    label: 'CHA2DS2-VASc Score',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'AFib stroke risk score',
    tooltip: '0: Low risk, 1: Moderate, ≥2: High (anticoagulation recommended)',
  },
  {
    name: 'var.qsofa_score',
    label: 'qSOFA Score',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Quick Sepsis-related Organ Failure Assessment',
    tooltip: '≥2: High risk of mortality, consider sepsis protocol',
  },
  {
    name: 'var.active_medication_count',
    label: 'Active Medication Count',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Number of active medications',
    tooltip: '≥10: Polypharmacy, increased risk of drug interactions',
  },
  {
    name: 'var.days_since_last_visit',
    label: 'Days Since Last Visit',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Days since last encounter',
    tooltip: 'Used for care gap identification',
  },
  {
    name: 'var.ejection_fraction',
    label: 'Ejection Fraction',
    type: 'number',
    inputType: 'number',
    category: FHIR_FIELD_CATEGORIES.COMPUTED,
    resource: 'Computed',
    fhirPath: 'computed',
    description: 'Left ventricular ejection fraction',
    tooltip: 'Normal: ≥55%. HFrEF: <40%. HFmrEF: 40-49%. HFpEF: ≥50%.',
    unit: '%',
  },
];

/**
 * Get fields by category
 */
export function getFieldsByCategory(category: string): FHIRFieldEnterprise[] {
  return FHIR_FIELDS_ENTERPRISE.filter((f) => f.category === category);
}

/**
 * Get field by name
 */
export function getFieldByName(name: string): FHIRFieldEnterprise | undefined {
  return FHIR_FIELDS_ENTERPRISE.find((f) => f.name === name);
}

/**
 * Get all categories with field counts
 */
export function getCategoriesWithCounts() {
  const counts: Record<string, number> = {};
  FHIR_FIELDS_ENTERPRISE.forEach((field) => {
    counts[field.category] = (counts[field.category] || 0) + 1;
  });
  return Object.entries(FHIR_FIELD_CATEGORIES).map(([key, label]) => ({
    key,
    label,
    count: counts[label] || 0,
  }));
}

/**
 * Get all temporal operators
 */
export function getTemporalOperators(): FHIRFieldEnterprise[] {
  return FHIR_FIELDS_ENTERPRISE.filter((f) => f.type === 'temporal');
}

/**
 * Get all workflow actions
 */
export function getWorkflowActions(): FHIRFieldEnterprise[] {
  return FHIR_FIELDS_ENTERPRISE.filter((f) => f.type === 'action');
}

/**
 * Search fields by keyword
 */
export function searchFields(keyword: string): FHIRFieldEnterprise[] {
  const lowerKeyword = keyword.toLowerCase();
  return FHIR_FIELDS_ENTERPRISE.filter(
    (f) =>
      f.name.toLowerCase().includes(lowerKeyword) ||
      f.label.toLowerCase().includes(lowerKeyword) ||
      f.description?.toLowerCase().includes(lowerKeyword) ||
      f.tooltip?.toLowerCase().includes(lowerKeyword)
  );
}
