name: Build and Push EHR Web

on:
  push:
    branches:
      - main
      - develop
      - staging
    paths:
      - 'ehr-web/**'
      - '.github/workflows/build-and-push-web.yml'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'ehr-web/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: ehr-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            # For main branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=prod,enable={{is_default_branch}}

            # For develop branch
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/develop' }}

            # For staging branch
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}

            # For version tags (v1.0.0)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

            # SHA for all builds
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./ehr-web
          file: ./ehr-web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
          # Build args for Next.js public env vars (placeholders, will be overridden at runtime)
          build-args: |
            NEXT_PUBLIC_API_URL=__RUNTIME_PLACEHOLDER__
            NEXT_PUBLIC_KEYCLOAK_URL=__RUNTIME_PLACEHOLDER__
            NEXT_PUBLIC_KEYCLOAK_REALM=__RUNTIME_PLACEHOLDER__
            NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=__RUNTIME_PLACEHOLDER__

      - name: Update deployment status
        if: success()
        run: |
          echo "✅ Successfully built and pushed ${{ env.IMAGE_NAME }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"

      - name: Create GitHub Release (for version tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: EHR Web ${{ github.ref_name }}
          body: |
            ## Docker Images
            - `docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}`
            - `docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest`
          draft: false
          prerelease: false
